// SPDX-FileCopyrightText: 2026 Seleshi Yalew and Fairflow contributors
// SPDX-License-Identifier: MIT
//
// ADR 0002: the TypeScript engine is a mirror. It must reproduce every golden vector generated by the authoritative
// Python engine (packages/engine-py/scripts/generate_vectors.py). Expected values are never written in this file.

import { describe, expect, it } from 'vitest';
import { resolveSeason, type SeasonInput } from './resolveSeason.js';
import { verdict } from './verdict.js';
import conformance from '../fixtures/conformance.json' with { type: 'json' };
import beta from '../fixtures/default-basin-beta.json' with { type: 'json' };

/** Both engines round to 1e-6 (§7.2); a last-bit difference before rounding can move one step. Large sums
 * (raw PWF) are compared relatively. */
const ROUNDING_STEP = 1e-6;
const RELATIVE = 1e-9;

function compare(got: unknown, want: unknown, path: string, diffs: string[]): void {
  if (typeof want === 'number') {
    const ok = typeof got === 'number' && Math.abs(got - want) <= ROUNDING_STEP + RELATIVE * Math.abs(want) + Number.EPSILON;
    if (!ok) diffs.push(`${path}: mirror ${String(got)} vs python ${want}`);
  } else if (Array.isArray(want)) {
    if (!Array.isArray(got) || got.length !== want.length) { diffs.push(`${path}: length differs`); return; }
    want.forEach((w, i) => compare(got[i], w, `${path}[${i}]`, diffs));
  } else if (want && typeof want === 'object') {
    for (const [k, w] of Object.entries(want)) compare((got as Record<string, unknown>)?.[k], w, `${path}.${k}`, diffs);
  } else if (got !== want) diffs.push(`${path}: mirror ${String(got)} vs python ${String(want)}`);
}

describe('mirror reproduces the Python golden vectors', () => {
  type Case = { label: string; input: SeasonInput; expected: unknown };
  for (const c of conformance.cases as unknown as Case[]) {
    it(c.label, () => {
      const diffs: string[] = [];
      compare(resolveSeason(c.input), c.expected, 'result', diffs);
      expect(diffs).toEqual([]);
    });
  }
});

describe('mirror reproduces the Python β fixture set (§3)', () => {
  type Row = { lens: SeasonInput['lens']; lensParams: SeasonInput['lensParams']; expected: unknown };
  for (const card of ['wet', 'normal', 'dry'] as const) {
    for (const row of beta[card] as unknown as Row[]) {
      it(`${card} ${row.lens}`, () => {
        const diffs: string[] = [];
        const input: SeasonInput = {
          schemes: beta.schemes, basin: beta.basin as SeasonInput['basin'], inflow: beta.inflow[card],
          stock: beta.basin.aquifer.initial, lens: row.lens, lensParams: row.lensParams, pumps: beta.schemes.map(() => 0),
          scoring: beta.scoring,
        };
        compare(resolveSeason(input), row.expected, 'result', diffs);
        expect(diffs).toEqual([]);
      });
    }
  }
});

describe('mirror reproduces the Python verdicts (§2.7)', () => {
  type VerdictCase = { label: string; input: { schemes: SeasonInput['schemes']; allocable: number; W: number[]; voted: SeasonInput['lens'];
    pumpingGap: number; lenses: { id: SeasonInput['lens']; params: SeasonInput['lensParams'] }[]; survivalFloor: number }; expected: unknown };
  for (const c of conformance.verdicts as unknown as VerdictCase[]) {
    it(c.label, () => {
      const i = c.input; const diffs: string[] = [];
      compare(verdict(i.schemes, i.allocable, i.W, i.voted, i.pumpingGap, i.lenses, i.survivalFloor), c.expected, 'verdict', diffs);
      expect(diffs).toEqual([]);
    });
  }
});
